name: todo_repository
description: Repository that manages the Todo domain

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  equatable: ^1.2.5

dev_dependencies:
  very_good_analysis: ^1.0.2